# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './QtDesigner/mainwindow_project.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(520, 453)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.user_temp = QtWidgets.QSlider(self.centralwidget)
        self.user_temp.setGeometry(QtCore.QRect(40, 50, 16, 160))
        self.user_temp.setMaximum(9000)
        self.user_temp.setSingleStep(1)
        self.user_temp.setOrientation(QtCore.Qt.Vertical)
        self.user_temp.setObjectName("user_temp")
        self.actual_temp = QtWidgets.QSlider(self.centralwidget)
        self.actual_temp.setGeometry(QtCore.QRect(40, 220, 16, 160))
        self.actual_temp.setMaximum(10000)
        self.actual_temp.setOrientation(QtCore.Qt.Vertical)
        self.actual_temp.setObjectName("actual_temp")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 50, 71, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 220, 101, 17))
        self.label_2.setObjectName("label_2")
        self.lcd_fuzzy_output = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_fuzzy_output.setGeometry(QtCore.QRect(340, 150, 151, 61))
        self.lcd_fuzzy_output.setObjectName("lcd_fuzzy_output")
        self.lcd_user_temp = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_user_temp.setGeometry(QtCore.QRect(60, 70, 64, 23))
        self.lcd_user_temp.setObjectName("lcd_user_temp")
        self.lcd_actual_temp = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_actual_temp.setGeometry(QtCore.QRect(60, 240, 64, 23))
        self.lcd_actual_temp.setObjectName("lcd_actual_temp")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(340, 130, 81, 21))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 520, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "User temp"))
        self.label_2.setText(_translate("MainWindow", "Actual temp"))
        self.label_3.setText(_translate("MainWindow", "Angel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
